ALTER TABLE "Lead"
  ALTER COLUMN "leadScore" SET DEFAULT 0;

UPDATE "Lead"
SET "leadScore" = 0
WHERE "leadScore" IS NULL;

ALTER TABLE "Lead"
  ALTER COLUMN "leadScore" SET NOT NULL;

ALTER TABLE "Lead"
  ADD COLUMN IF NOT EXISTS "leadScoreUpdatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
