ALTER TYPE "LeadType" ADD VALUE IF NOT EXISTS 'PHONE_UP';
ALTER TYPE "LeadType" ADD VALUE IF NOT EXISTS 'WALK_IN';
ALTER TYPE "LeadType" ADD VALUE IF NOT EXISTS 'INTERNET';
ALTER TYPE "LeadType" ADD VALUE IF NOT EXISTS 'OTHER';
